package automationteststore.candidateTestData;

public class AdditionalCautionsDeclareNowOrLaterPageTestData {
	public static final String ADDITIONAL_CAUTIONS_DECLARE_NOW_OR_LATER_PAGE_TO_ADDITIONAL_CAUTIONS_DETAILS_PAGE_SELECTION = "Now";
	public static final String ADDITIONAL_CAUTIONS_DECLARE_NOW_OR_LATER_PAGE_TO_EQUALITY_AND_DIVERSITY_PAUSE_PAGE_SELECTION = "Later";
}
