package automationteststore.candidateTestData;

public class AdditionalConvictionsDeclareNowOrLaterPageTestData {
	public static final String ADDITIONAL_CONVICTIONS_DECLARE_NOW_OR_LATER_PAGE_TO_ADDITIONAL_CONVICTIONS_DETAILS_PAGE_SELECTION = "Now";
	public static final String ADDITIONAL_CONVICTIONS_DECLARE_NOW_OR_LATER_PAGE_TO_ADDITIONAL_CAUTIONS_QUESTION_PAGE_SELECTION = "Later";
}
